Adds contributing doc and updates README
redwoodjs/redwoodjs.com pull request #291
Opened 2020-08-13 11:12 UTC by alvincrespo

This PR syncs documentation approach with the primary Redwood repo by creating a CONTRIBUTING.md file and updating the README with some additional info (forums, chats, issue search).

## Changes

- Creates CONTRIBUTING.md
- Moves Contributing and Local Development sections from README to CONTRIBUTING.md
- Updates README with "good first issue" search, forums and discord links

2020-08-31 10:27 UTC, alvincrespo commented
Hi all! Just wanted to see if there was any feedback I could take care of on this PR?

2020-08-31 20:26 UTC, cannikin commented
@thedavidprice Does this still work with the new contributors list in the README of the main repo?

2020-09-02 04:24 UTC, thedavidprice commented
Ah, sorry this one slipped under my radar, gents. I'll loop back with comments tomorrow.

Thanks for pinging us @alvincrespo!

2020-09-12 19:45 UTC, thedavidprice requested changes

2020-09-12 19:45 UTC, thedavidprice commented on CONTRIBUTING.md
> +
Add copy here at the top with links to docs to get started, i.e. Read these first:
- Code of conduct: https://github.com/redwoodjs/redwood/blob/main/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct
- Contributing: https://redwoodjs.com/docs/contributing#contributing-docs

Maybe this should be something like `## Before you start`

2020-09-12 19:45 UTC, thedavidprice commented on CONTRIBUTING.md
> +
We do have specific information about Docs: setup/structure and how to write. I'd like to see a specific section (maybe `## Contributing Docs`) that calls this out and links to:
https://redwoodjs.com/docs/contributing#contributing-docs

2020-09-12 19:45 UTC, thedavidprice commented on CONTRIBUTING.md
> +Copy `.env.example` to a file named `.env` and get API keys/IDs for all of the service listed. Alternatively, if you don't care about populating search comment out the `require` statement for `search
The second sentence here no longer applies and should be removed --> starting with "Alternatively..." and through the end of the paragraph. In a recent PR, a fix was added for local dev to run fine even when Env Vars are not available. So maybe add that as an explanation.

2020-09-12 19:45 UTC, thedavidprice commented on README.md
>  Other documentation is pulled from various READMEs in the main [redwoodjs/redwood](https://github.com/redwoodjs/redwood) repo (see `lib/build.js`, the `SECTIONS` constant).
This isn't up to date and probably doesn't belong here. Try this:
- move this info to the new `## Contributing Docs` section of CONTRIBUTING.md
- all docs are in `docs/` (and, for those that are not, there's a placeholder with link to the location, which does not need to be explained)
- the Tutorial is /TUTORIAL.md

2020-09-12 19:45 UTC, thedavidprice commented on README.md
This should be moved to the intro section of /CONTRIBUTING.md

2020-09-12 19:45 UTC, thedavidprice commented on README.md
> +Check out [CONTRIBUTING.md](./CONTRIBUTING.md) for additional instructions on how to get started and submit a PR.
```suggestion
Check out [CONTRIBUTING.md](./CONTRIBUTING.md) for instructions to get started and submit a PR.
```

2020-09-12 19:47 UTC, thedavidprice commented
@alvincrespo I (finally) got to this review. In general, breaking the content into 2 docs makes a ton of sense. However, there's just a lot of information that needs to be changed or is missing (a lot has been modified since this was written). So the review comments I made will help make this a lot more useful + accurate. Thank you!

2020-09-12 20:00 UTC, thedavidprice commented on CONTRIBUTING.md
> +
Just remembered one more thing we need to add, project Leads. This helps new contributors know who to reach out to for help and Reviews. See this for a simple example: https://github.com/redwoodjs/redwood/tree/main/tasks/all-contributors#Package-Lead

There are three people who are primarily responsible for Reviews and merging PRs:
- `@cannikin`: website, Tutorial, and Docs
- `@jtoar`: Docs
- `@thedavidprice`: Docs

2021-09-18 00:00 UTC, closed without merging