update tutorial 'Saving Data' section to use Flash
redwoodjs/redwoodjs.com pull request #344
Opened 2020-09-07 02:43 UTC by forresthayes

references issues #318 and #204

I tried to update all the code samples to reflect the change. Please let me know if you catch any inconsistencies.

Thanks!

2020-09-10 12:48 UTC, guledali commented
@cannikin  @thedavidprice  Any chance that this could get merged?

2020-09-10 14:16 UTC, thedavidprice commented
@cannikin this one needs your eyes.

2020-09-10 15:58 UTC, cannikin requested changes

2020-09-10 15:58 UTC, cannikin commented on TUTORIAL.md
We'll need to replace this screenshot with one showing the Flash

2020-09-10 15:58 UTC, cannikin commented on TUTORIAL.md
> +        classes: 'rw-flash-success',
Although this style will make the Flash look really nice, this `rw-flash-success` class is coming out of nowhere...I don't want people to think there's some secret list of classes that we just forgot to introduce to them. Also, if you haven't scaffolded anything, you won't have that CSS class present (of course the tutorial includes a couple of scaffolds so anyone following through from start will have it, but we don't explicitly say that anywhere). Can we just do some inline styles here, like with the rest of the tutorial?

I'm not sure if `addMessage` supports sending in a `style` attribute but we should add that functionality, if not. It could be pretty simple like:

    style: { backgroundColor: 'green', color: 'white', padding: '1rem' }

2020-09-10 15:58 UTC, cannikin commented on TUTORIAL.md
> +        classes: 'rw-flash-success',
Same `style` change as above.

2020-09-10 18:41 UTC, forresthayes commented on TUTORIAL.md
> +        classes: 'rw-flash-success',
good call! I'll look into using a style attribute.

2020-09-11 17:03 UTC, forresthayes commented
@peterp approved the [new Flash style option](redwoodjs/redwood#1133) for the next release.

2020-09-11 17:14 UTC, peterp commented
You wrote the docs too! Amazing!

2020-09-17 15:39 UTC, cannikin requested changes
Thanks for the style updates! Any chance we can get a screenshot that shows the message in action?

2020-09-18 22:10 UTC, forresthayes commented
@cannikin, I have a screenshot that might work. 

What is your approach to uploading your screenshots to GitHub? I see that dragging the file into this reply created a GitHub link. Do you embed that link directly into TUTORIAL.md?

Thanks!

![redwoodjs-tutorial-saving-data-submit-flash](https://user-images.githubusercontent.com/44448047/93649232-1be9a700-f9d1-11ea-821c-7a69c626f50c.png)

2020-09-18 23:16 UTC, cannikin commented
BEAUTIFUL!

Yep, I just use GitHub comments as my image CDN. haha I'll upload one to a comment box and just copy out the URL and paste into my .md file!

2020-09-19 18:08 UTC, cannikin approved these changes

2020-09-19 18:08 UTC, cannikin commented
Thank you sir!

2020-09-19 18:08 UTC, merged