Added Hacktoberfest Banner to home page
redwoodjs/redwoodjs.com pull request #394
Opened 2020-10-03 21:56 UTC by Burnsy

![image](https://user-images.githubusercontent.com/15834048/95002408-84d53f80-05cb-11eb-96f3-770f9cf1450c.png)

Built a quick banner for Hacktoberfest, I could not get it dev working locally so it's built blind and in-browser!  

But it should look the same!

2020-10-04 01:45 UTC, thedavidprice commented
Just a quick look for now. Will review soon. Thank you @Burnsy 🚀

What do you think about linking to this Issue?

https://github.com/redwoodjs/redwood/issues/1266

2020-10-04 07:38 UTC, Burnsy commented
It already is linked to it!

2020-10-04 16:15 UTC, thedavidprice commented
@Burnsy @cannikin What do you think about this:

<img width="1048" alt="Screen Shot 2020-10-04 at 9 07 58 AM" src="https://user-images.githubusercontent.com/2951/95020719-9e08db00-0621-11eb-963c-ff392b138157.png">
---
<img width="477" alt="Screen Shot 2020-10-04 at 9 11 08 AM" src="https://user-images.githubusercontent.com/2951/95020721-a06b3500-0621-11eb-8ac0-a2228b6135aa.png">

### Here's what I did:
- increased padding-top/bottom from 3 to 5
- font extra-bold
- replaced button text (note: "RedwoodJS", no `.`)
- on mobile, centered top text
- Change link to this Issue in Framework: https://github.com/redwoodjs/redwood/issues/1266

2020-10-04 16:16 UTC, Burnsy commented
Looks great! 🔥

2020-10-05 15:43 UTC, cannikin approved these changes

2020-10-05 16:58 UTC, thedavidprice commented
@Burnsy To be clear, I **did not** make any code changes. That's just a mockup from the browser.

Given that everyone's agreed on the display, can you please make the changes in the code? There's no way I can get to to today. Thanks in advance!

2020-10-05 16:59 UTC, thedavidprice commented on code/html/layouts/application.html
> +      <div class="bg-hacktoberfest-blue-500">
Make styling changes per:
https://github.com/redwoodjs/redwoodjs.com/pull/394#issuecomment-703278572

2020-10-05 16:59 UTC, thedavidprice requested changes
See inline comment re:
https://github.com/redwoodjs/redwoodjs.com/pull/394#issuecomment-703278572

2020-10-05 17:23 UTC, Burnsy commented
Done 🎉  @thedavidprice

2020-10-05 17:53 UTC, merged

2020-10-05 17:55 UTC, thedavidprice commented
![ship it squirrel](https://user-images.githubusercontent.com/2951/95114711-33c36980-06f9-11eb-866b-c7be05ae2ac0.png)