Added setup command
redwoodjs/redwoodjs.com pull request #410
Opened 2020-10-11 22:56 UTC by lumenCodes

I am not sure if the section I added but please review this @thedavidprice , so I can make necessary changes if any.

2020-10-13 00:13 UTC, thedavidprice requested changes
Headed in the right direction. Made notes for next steps. Just let me know if you have any further questions.

2020-10-13 00:13 UTC, thedavidprice commented on docs/cliCommands.md
> +Use "yarn rw setup" command. See setup command [here](https://redwoodjs.com/reference/command-line-interface#setup)
```suggestion
This command is **deprecated** in favor of `yarn rw setup <command>`. See Setup command [here](https://redwoodjs.com/reference/command-line-interface#setup)
```

Let's try that text above (you can commit or change directly). 

Also, let' remove the rest of the information from this section. See screenshot for red crossed out copy to remove:
<img width="687" alt="Screen Shot 2020-10-12 at 4 58 20 PM" src="https://user-images.githubusercontent.com/2951/95800583-90e88d80-0cac-11eb-8952-6e9412a87456.png">

2020-10-13 00:13 UTC, thedavidprice commented on docs/cliCommands.md
> +## setup command
```suggestion
## setup
```

Just setup is fine

2020-10-13 00:13 UTC, thedavidprice commented on docs/cliCommands.md
> +The setup command docs is a comprehensive reference of the Redwood CLI. See the [docs](https://redwoodjs.com/reference/command-line-interface#setup) for refrences.
This content section should look like the current Util command section. So start by removing the content from Util and pasting it here. There are other good examples on the CLI Docs page as well. 

Then change the content to reflect Setup specific information, which comes from the output help of the setup command itself:
```
$ rw setup --help

Initialize project config and install packages

Commands:
  rw setup i18n               Setup i18n
  rw setup tailwind         Setup tailwindcss and PostCSS
  rw setup webpack       Setup webpack in your project so you can add custom config

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                             [boolean]
```

2020-10-13 23:50 UTC, lumenCodes commented
Wow, that's a while lot of changes to be made. I will do them soon and get back to you.

Thank you so @thedavidprice for reviewing this. I am very grateful.

2020-10-14 08:13 UTC, lumenCodes commented on docs/builds.md
> +Also learn how to install in yarn (--dev or -D) as a dev dependency [here](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-dev-d).
Partly.... If I understood you well you mean that I should do a pull and then revert the changes I made?

2020-10-14 15:37 UTC, thedavidprice commented on docs/builds.md
> +Also learn how to install in yarn (--dev or -D) as a dev dependency [here](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-dev-d).
First, I just want to make sure you understand the PR process as it can be confusing sometimes:
1. you created a branch (from `main`) to work on updating `builds.md`
2. we edited your branch further, and then we merged the PR https://redwoodjs.com/docs/builds#steps-on-netlify
3. you can see the final updated page here: https://redwoodjs.com/docs/builds
4. And here is the current version of `builds.md` in the `main` branch: https://github.com/redwoodjs/redwoodjs.com/blob/main/docs/builds.md

What seems to have happened in _this_ branch is that you carried over your code for `builds.md` from Step 1 above. So now you have code that is _behind_ the current code for this file. 

What might fix this is merging `main` branch into this branch.
- make sure you are on `lumencodes-docs-390` in your project by running `git status`
- fetch all remote changes with `git fetch`
- merge changes from main into your branch with `git merge main`

If all else fails, manually you can just copy the current code for this file from `main` and past it into your branch's file.

2020-10-21 20:07 UTC, lumenCodes commented on docs/builds.md
> +Also learn how to install in yarn (--dev or -D) as a dev dependency [here](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-dev-d).
Ok I have done this

2020-10-22 04:10 UTC, lumenCodes commented
@thedavidprice I am so sorry this took a long time. But please check the changes I have made.
Thank you for your patience 😀

2020-10-24 06:04 UTC, thedavidprice commented
Hi @lumenCodes Because we released RedwoodJS `v0.20.0`, I needed to get this change in our Docs as the new Setup command is included in the release. So I had to effectively reset the branch and make the changes. Please do look at the final code I [added for reference](https://github.com/redwoodjs/redwoodjs.com/pull/410/files). You'll notice the `build.md` file is no longer included, I added the deprecation notice to `util`, and I add the new `setup` command.

It seems your difficulties came from managing the git process, including updating the branch and handling merge conflicts. (You had some merge conflict code included in your `cliCommands.md` code.

This process can take some time to learn and get the hang of, so I want to encourage you to keep going and try again with a new issue! Here are some tips for next steps to learn:
- Have you tried using [GitHub Desktop](https://desktop.github.com/)? It can be a helpful tool for managing the git and PR process.
- I recommend using [VS Code](https://code.visualstudio.com/) as your editor. It works very nicely with GitHub Desktop, especially for handling merge conflicts, comparing branches, and merging changes from one branch into another.
- These two courses on GitHub cover Markdown, merge conflicts and the PR process, which are the core skills you'll need to contribute to Redwood docs. Take a look if you have the time:
    - https://lab.github.com/githubtraining/first-day-on-github
    - https://lab.github.com/githubtraining/first-week-on-github
- One great way to practice is to go through the PR process on the repo fork you created. The idea is to try and update https://github.com/lumenCodes/redwoodjs.com with a PR, so you'll learn both sides of the process.

I hope all this helps and is encouraging. It just takes practice and trying again! And you're welcome to try again on another Issue. Can I recommend you try the following in a new PR? (No pressure of course.):
- Right now, the Setup command just lists the available command options (e.g. i18n, tailwind) in the "Commands" table. However, we'd like them to display in sub-heading and show up in the right column navigation.
- Using the [DB command](https://redwoodjs.com/docs/cli-commands#db) section as an example, can you add the sub-heading sections for i18n, tailwind, and webpack to the current Setup command?

You can get started by either creating an Issue to outline your plan and ask questions (if needed). Or, if you think you have enough grasp to take a next step, open a PR and outline your plan in the first comment.

Either way, please loop me in.

Lastly, I'm not the only person who's happy to help. We have a vibrant community that is available for you to ask questions and get advice. If you haven't already, please introduce yourself on:
- Chat: https://discord.gg/redwoodjs  
- Forums: https://community.redwoodjs.com

Keep me posted!

🚀

2020-10-24 06:05 UTC, merged

2020-10-31 19:13 UTC, lumenCodes commented
> Hi @lumenCodes Because we released RedwoodJS `v0.20.0`, I needed to get this change in our Docs as the new Setup command is included in the release. So I had to effectively reset the branch and make the changes. Please do look at the final code I [added for reference](https://github.com/redwoodjs/redwoodjs.com/pull/410/files). You'll notice the `build.md` file is no longer included, I added the deprecation notice to `util`, and I add the new `setup` command.
> 
> It seems your difficulties came from managing the git process, including updating the branch and handling merge conflicts. (You had some merge conflict code included in your `cliCommands.md` code.
> 
> This process can take some time to learn and get the hang of, so I want to encourage you to keep going and try again with a new issue! Here are some tips for next steps to learn:
> 
> * Have you tried using [GitHub Desktop](https://desktop.github.com/)? It can be a helpful tool for managing the git and PR process.
> * I recommend using [VS Code](https://code.visualstudio.com/) as your editor. It works very nicely with GitHub Desktop, especially for handling merge conflicts, comparing branches, and merging changes from one branch into another.
> * These two courses on GitHub cover Markdown, merge conflicts and the PR process, which are the core skills you'll need to contribute to Redwood docs. Take a look if you have the time:
>   
>   * https://lab.github.com/githubtraining/first-day-on-github
>   * https://lab.github.com/githubtraining/first-week-on-github
> * One great way to practice is to go through the PR process on the repo fork you created. The idea is to try and update https://github.com/lumenCodes/redwoodjs.com with a PR, so you'll learn both sides of the process.
> 
> I hope all this helps and is encouraging. It just takes practice and trying again! And you're welcome to try again on another Issue. Can I recommend you try the following in a new PR? (No pressure of course.):
> 
> * Right now, the Setup command just lists the available command options (e.g. i18n, tailwind) in the "Commands" table. However, we'd like them to display in sub-heading and show up in the right column navigation.
> * Using the [DB command](https://redwoodjs.com/docs/cli-commands#db) section as an example, can you add the sub-heading sections for i18n, tailwind, and webpack to the current Setup command?
> 
> You can get started by either creating an Issue to outline your plan and ask questions (if needed). Or, if you think you have enough grasp to take a next step, open a PR and outline your plan in the first comment.
> 
> Either way, please loop me in.
> 
> Lastly, I'm not the only person who's happy to help. We have a vibrant community that is available for you to ask questions and get advice. If you haven't already, please introduce yourself on:
> 
> * Chat: https://discord.gg/redwoodjs
> * Forums: https://community.redwoodjs.com
> 
> Keep me posted!
> 
> 🚀

Thank you so much @thedavidprice . I am really encouraged and feel welcomed to the redwoodjs community. I will sure be creating an issue soon. Though I don't know how long it will take but I am going to give it a shot. And I am going to reach out to you when I have an issue on that.

I will sure look at the tutorials and also use GitHub Desktop ☺️ .

2020-11-05 15:56 UTC, thedavidprice commented
@lumenCodes you're very welcome! And please do.