Tutorial improvements (Part 1)
redwoodjs/redwoodjs.com pull request #424
Opened 2020-10-18 16:04 UTC by brentguf

Hello, Redwood community 🌲

I'm trying to fully grasp Redwood and am going through the tutorial to do that. I have this tendency to rewrite tutorials I'm going through if they're open source (and it nicely helps with comprehension!). So I'm doing the same for Redwood's tutorial. For now it's been limited to adding more headers in the first few parts.

Before I spend time making changes like this, I wanted to check if such changes will be considered (i.e. if I'm allowed to touch the structure of the pages/tutorial).

There are also a bunch of changes due to my editor formatting settings (disabled now) and some auto-generated changes. Apologies for that. Let me know if there is a problem and I'll see to remove them.

Finally, is there a way for me to build the pages locally in such a way that they more or less resemble the real tutorial website? I did the build mentioned in the docs, but it doesn't produce a useful result.

Thanks!

2020-10-18 21:05 UTC, Tobbe commented
@brentguf Thanks for taking the time to go through the tutorial and leaving your feedback! 🙂 

> PS1: is there a way for me to build the pages locally in such a way that they more or less resemble the real tutorial website? I did the build mentioned in the docs, but it doesn't produce a useful result.

What did you try, and what was the result? It should be as simple as `yarn install` `yarn build` `yarn dev` and then just go to http://127.0.0.1:8080

2020-10-19 17:27 UTC, cannikin requested changes

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +- Yarn: ">=1.15"
We kept these lowercase to sort of reference the actual command utilities, `node` and `yarn` rather than the proper names used in the preceding sentence.

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +### Generating the Home page
We don't include subheadings directly under a "main" heading. Page breaks occur at level 2 and we use level 3 and higher to generate the "On this page" link map that appears at the right on XL sized displays (>= 1280 pixels wide). In this case both links would go to effectively the same place. The opening paragraph under the "main" heading sets the context for what we're building, I don't feel like we also need a heading calling it out here.

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +### Auto-reloading
The fact that the browser is auto-reloading doesn't feel like a big enough thing that it needs its own heading here...these are usually reserved for when the direction of the text changes to a new context (building something new) but in this case auto-reloading is just mentioned in a sort of "oh, by the way..." kind of deal.

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +### Generating the About page
Same thing as the "Generating the Home Page" comment above

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +### Creating a Link to our new About page
This whole section is only a few paragraphs long, I don't feel like it really needs these header breaks...

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +### Creating a link to the Home page from the About page
Same as previous comment

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +      />
Your Prettier config may be adding weird whitespace here

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +        />
More whitespace

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +        />
Whitespace

2020-10-19 17:27 UTC, cannikin commented on TUTORIAL.md
> +        />
Whitespace

2020-10-19 17:27 UTC, cannikin commented on code/html/index.html
> +@@layout("application", { "title": "RedwoodJS - Bringing Full-stack to the Jamstack", "version": "v0.19.3" })
Our build script keeps this number updated automatically, you should ignore this change when committing.

2020-10-19 17:27 UTC, cannikin commented on code/html/logos.html
> +@@layout("application", { "title": "RedwoodJS - Bringing Full-stack to the Jamstack", "version": "v0.19.3" })
Same as previous

2020-10-19 17:27 UTC, cannikin commented on code/html/roadmap.html
> +@@layout("application", { "title": "Roadmap : RedwoodJS Docs", "version": "v0.19.3" })
Same as previous

2020-10-19 17:27 UTC, cannikin commented on code/html/stickers-thanks.html
> +@@layout("application", { "title": "RedwoodJS - Get a sticker!", "version": "v0.19.3" })
Same as previous

2020-10-19 17:27 UTC, cannikin commented on code/html/stickers.html
> +@@layout("application", { "title": "RedwoodJS - Get a sticker!", "version": "v0.19.3" })
Same as previous

2020-10-19 17:29 UTC, cannikin commented
Hello @brentguf! 

> PS2: could you write some instructions on how to run Prettier for this repo? I had to undo my changes manually because I couldn't figure it out.

Hmm, if you have Prettier installed it should "just work" as we've got a prettier.config.js in the root of the repo here. I'm not an expert on Prettier by any means though...what problems are you seeing?

2020-10-19 19:06 UTC, brentguf commented on TUTORIAL.md
> +- Yarn: ">=1.15"
Gotcha! Changed it back.

2020-10-19 19:10 UTC, brentguf commented on TUTORIAL.md
> +### Generating the Home page
I see the problem with the 'On this page' ToC. For me personally, these extra headers help to have a better overview, process the material quicker and find the spot where I left the tutorial to go to my code editor, that's why I added them. Will remove them again!

2020-10-19 19:11 UTC, brentguf commented
> Hello @brentguf!
> 
> > PS2: could you write some instructions on how to run Prettier for this repo? I had to undo my changes manually because I couldn't figure it out.
> 
> Hmm, if you have Prettier installed it should "just work" as we've got a prettier.config.js in the root of the repo here. I'm not an expert on Prettier by any means though...what problems are you seeing?

Hi Rob! I'll try to figure it out myself. I think there's a clash somewhere with my VSCode settings. I have similar trouble at work. 

Thanks for taking the time to give some feedback!

2020-10-19 19:12 UTC, brentguf commented
Hi @cannikin! I think there's a clash somewhere with my VSCode settings. I'll try to figure it out myself.

Thanks for taking the time to give some feedback!

2020-10-19 19:48 UTC, brentguf commented
> @brentguf Thanks for taking the time to go through the tutorial and leaving your feedback! 🙂
> 
> > PS1: is there a way for me to build the pages locally in such a way that they more or less resemble the real tutorial website? I did the build mentioned in the docs, but it doesn't produce a useful result.
> 
> What did you try, and what was the result? It should be as simple as `yarn install` `yarn build` `yarn dev` and then just go to http://127.0.0.1:8080

Hi @Tobbe,

I did yarn install, yarn build and then yarn dev. At yarn dev, I receive the following error. I had it before with a different project, but can't find anymore how I fixed it. Do you happen to know?

```
Error: Cannot find module 'fs/promises'
Require stack:
- /mnt/c/Users/myusername/Desktop/redwoodjs.com/lib/middleware/use-redirects.js        
- /mnt/c/Users/myusername/Desktop/redwoodjs.com/node_modules/live-server/index.js      
- /mnt/c/Users/myusername/Desktop/redwoodjs.com/node_modules/live-server/live-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/mnt/c/Users/brent_52wnxbs/Desktop/redwoodjs.com/lib/middleware/use-redirects.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/myusername/Desktop/redwoodjs.com/lib/middleware/use-redirects.js',
    '/mnt/c/Users/myusername/Desktop/redwoodjs.com/node_modules/live-server/index.js',
    '/mnt/c/Users/myusername/Desktop/redwoodjs.com/node_modules/live-server/live-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also, do you receive a link to 8080 in your terminal? I didn't think of checking the toml file for this 8080 port, so if the terminal output doesn't mention it, it might be unclear for other people too.

2020-10-19 19:53 UTC, Tobbe commented
> Also, does the terminal mention a link to 8080 after running yarn dev successfully?

Yes, it says `Serving "C:\Users\tobbe\dev\redwood\redwoodjs.com" at http://127.0.0.1:8080`

It looks like you're using WSL. I haven't tried running redwoodjs.com in that environment. So it could be something there... Also what node version are you using?

2020-10-19 21:00 UTC, brentguf commented
> It looks like you're using WSL. I haven't tried running redwoodjs.com in that environment. So it could be something there... Also what node version are you using?

I also tried Powershell, which produces the same error...

I'm using v12.19 of node. Maybe I should open an issue rather that discuss it in this PR?

2020-10-19 21:03 UTC, Tobbe commented
> Maybe I should open an issue rather that discuss it in this PR?

👍

2020-10-22 17:11 UTC, cannikin commented
@brentguf This is looking great, thanks again! Only thing left are those version numbers that got updated (I've got comments on them in the code review). Can you revert those? Other than that it's good to go!

2020-10-22 19:51 UTC, brentguf commented
@cannikin Sure, I misunderstood your comment. Just made the changes! 

Are the `data-turbolinks="false"` changes fine? They were also autogenerated.

2020-10-23 18:17 UTC, cannikin commented
Yep those `turbolinks` are okay, I'm surprised they weren't there to start with, actually. MERGING

2020-10-23 18:17 UTC, merged

2020-10-23 18:17 UTC, cannikin commented
Thanks again!