Tutorial: Cells
redwoodjs/redwoodjs.com pull request #427
Opened 2020-10-22 22:42 UTC by brentguf

2020-10-22 22:46 UTC, brentguf commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
I've read the original text (see quote below) a few times, as well as watched the tutorial on YouTube. 

> You will need _some_ kind of indication that you're using more than one word. Calling `yarn redwood g cell blogposts` will generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js`

Based on that, I rewrote this part. I'm still not convinced that I understood correctly what the original text tried to say, so let me know if I interpreted it wrongly.

2020-10-22 22:47 UTC, brentguf commented on TUTORIAL.md
> +To get you off and running as quickly as possible the generator assumes you've got a root GraphQL query named the same thing as your cell and gives you the minimum query needed to get something out o
I had to move back and forth a bit to follow with this part, so added some clarifications (code example + file references).

2020-10-22 22:48 UTC, brentguf commented on TUTORIAL.md
> +      <div>Posted at: <time datetime={post.createdAt}>{post.createdAt}</time></div>
Semantic HTML

2020-10-22 22:54 UTC, Tobbe commented on TUTORIAL.md
> +We'll have to rename that to just `posts` in both the query name and prop named in `Success`:
```suggestion
We'll have to rename that to just `posts` in both the query name and in the prop name in `Success`:
```

2020-10-22 23:01 UTC, Tobbe commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
No offence, but tbh I think it was better the way it was originally...

What the tutorial is trying to say is that while both you and I know "blogposts" are two words put together, the generator doesn't know that. So you'll have to give it some kind of hint. Either by fully doing the correct capitalization yourself ("BlogPosts"), or at least make the "p" capital ("blogPosts"). Your other options are to separate the two words with a dash or an underscore, and the generator will know to name the cell BlogPostsCell

2020-10-22 23:07 UTC, brentguf commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
No offence taken ;-) I agree. 

What I did was: I very explicitely wrote how I understood it, so someone could correct me and with the idea to change it again after it's clear. So I will change it again.

Thanks.

2020-10-23 18:39 UTC, cannikin requested changes

2020-10-23 18:39 UTC, cannikin commented on TUTORIAL.md
> +      <div>Posted at: <time datetime={post.createdAt}>{post.createdAt}</time></div>
I purposely left out the `<time>` tag here to keep the code simpler and just focus on getting the post data displayed. In part 2 of the tutorial we add Comments and at that point I talk about the `<time>` tag and even add a test for its presence!

2020-10-23 18:39 UTC, cannikin commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
Hmmm...I'm not loving this restructure. I like the flow better of showing users the examples of possible syntax first and then giving the counter example (no case change). 

I'd probably just add a clarification around what "more than one word" means after your note about how you were confused. Something like:

> You will need _some_ kind of indication that you're using more than one word ("blog" and "posts"). Just calling `yarn redwood g cell blogposts` would generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js` which, in this case, is not what we want.

2020-10-25 15:02 UTC, brentguf commented on TUTORIAL.md
> +      <div>Posted at: <time datetime={post.createdAt}>{post.createdAt}</time></div>
Great, removed it again!

2020-10-25 15:04 UTC, brentguf commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
@cannikin I kept the structure now and added some clarifications. I didn't notice that was a counter example, so I also clarified that.

Let me know if you can live with my suggested changes. :)

2020-10-26 20:28 UTC, cannikin requested changes

2020-10-26 20:28 UTC, cannikin commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
> Calling `yarn redwood g cell blogposts` will generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js`. These will all create the same filename:

This all ran together for me and it sounded like the command `yarn redwood g cell blogposts` (the command we're demonstrating as the "wrong" command) would somehow create the four variants listed right after...I feel like there should at least be a paragraph break before the "These will all create..." sentance.

However, I still prefer the original way: show the correct command(s) first (using camelCase or snake-case) and then an explanation of why we're doing it that way, with the counter-example of what happens when you try just "blogposts".

2020-10-26 21:19 UTC, brentguf commented on TUTORIAL.md
> +> When generating cells you can use any case you'd like and Redwood will do the right thing when it comes to naming. However, for our use case you will need _some_ kind of indication that you're usin
@cannikin Thanks for some more clarifications! Are you sure that you checked the latest version of the file? This is what it looks like now:

> **Indicating Multiplicity to the Cell Generator**
>
> When generating a cell you can use any case you'd like and Redwood will do the right thing when it comes to naming. These will all create the same filename (`web/src/components/BlogPostsCell/BlogPostsCell.js`):
>
>     yarn rw g cell blog_posts
>     yarn rw g cell blog-posts
>     yarn rw g cell blogPosts
>     yarn rw g cell BlogPosts
>
> You will need _some_ kind of indication that you're using more than one word: either snake_case (`blog_posts`), kebab-case (`blog-posts`), camelCase (`blogPosts`) or PascalCase (`BlogPosts`). 
> 
> Calling `yarn redwood g cell blogposts` (without any indication that we're using two words) will generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js`.

Let me know if there's still anything you'd like to change!

2020-10-26 21:20 UTC, brentguf commented
@cannikin Thanks for some more clarifications! Are you sure that you checked the latest version of the file? This is what it looks like now:

> **Indicating Multiplicity to the Cell Generator**
>
> When generating a cell you can use any case you'd like and Redwood will do the right thing when it comes to naming. These will all create the same filename (`web/src/components/BlogPostsCell/BlogPostsCell.js`):
>
>     yarn rw g cell blog_posts
>     yarn rw g cell blog-posts
>     yarn rw g cell blogPosts
>     yarn rw g cell BlogPosts
>
> You will need _some_ kind of indication that you're using more than one word: either snake_case (`blog_posts`), kebab-case (`blog-posts`), camelCase (`blogPosts`) or PascalCase (`BlogPosts`). 
> 
> Calling `yarn redwood g cell blogposts` (without any indication that we're using two words) will generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js`.

Let me know if there's still anything you'd like to change!

2020-10-26 21:22 UTC, brentguf commented
@cannikin Thanks for the clarifications, made some more changes! Are you sure that you were checking the latest version of the file before? This is what it looks like now:

> **Indicating Multiplicity to the Cell Generator**
>
> When generating a cell you can use any case you'd like and Redwood will do the right thing when it comes to naming. These will all create the same filename (`web/src/components/BlogPostsCell/BlogPostsCell.js`):
>
>     yarn rw g cell blog_posts
>     yarn rw g cell blog-posts
>     yarn rw g cell blogPosts
>     yarn rw g cell BlogPosts
>
> You will need _some_ kind of indication that you're using more than one word: either snake_case (`blog_posts`), kebab-case (`blog-posts`), camelCase (`blogPosts`) or PascalCase (`BlogPosts`). 
> 
> Calling `yarn redwood g cell blogposts` (without any indication that we're using two words) will generate a file at `web/src/components/BlogpostsCell/BlogpostsCell.js`.

Let me know if there's still anything you'd like to change!

2020-10-26 21:58 UTC, cannikin commented
That sounds great, weird that it doesn't show like that in the diff for me?

![image](https://user-images.githubusercontent.com/300/97233166-b80a8900-179b-11eb-93e9-fc4b344e4892.png)

2020-10-26 22:00 UTC, cannikin commented
Hmmmm went back over to the Files tab manually and now it does! I have no idea what GitHub is doing sometimes. :(

2020-10-26 22:00 UTC, merged