Add serverfull hosting recipe to cookbook
redwoodjs/redwoodjs.com pull request #431
Opened 2020-10-24 11:58 UTC by njjkgeerts

Adding a serverfull hosting recipe to the cookbook.
Forum discussion: https://community.redwoodjs.com/t/serverfull-hosting/1182

2020-10-24 18:47 UTC, Tobbe approved these changes

2020-10-24 22:08 UTC, ajcwebdev commented
Noticed a tiny typo in the Nginx section, essential is missing an i:

>Please note that the trailing slash in the proxy_pass value is essental to correctly map the API functions.

2020-10-26 19:20 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +A code example can be found at: https://github.com/njjkgeerts/redwood-pm2
I'd recommend moving this to the top introduction section — starting with examples seems to help add meaning to the implementation steps. Also, what do you think about a link to the live example app http://redwood-pm2.nickgeerts.com ?

2020-10-26 19:20 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +- There is a Prisma bug that occurs in Node.js version 12, so use version 14
This is no longer the case as of Redwood v0.20.0 (including Prisma 2.9.0)

2020-10-26 19:24 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +- The API only runs in fork mode in PM2, not cluster mode
I'd recommend adding this as a callout in the applicable API setup section, e.g. in either "Project" or "PM2". You can create a callout using markdown `>` for blockquote.

> This is a blockquote example

2020-10-26 19:25 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +- Yarn
What do you think about adding links to docs/websites for these, especially Nginx and PM2?

2020-10-26 19:28 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +better clarity.
```suggestion
Create a PM2 ecosystem configuration file. For clarity, it's recommended to rename `ecosystem.config.js` to something like `pm2.config.js`.
```

Using the first person "I" can be a bit confusing. Not a real issue, but something like the above is probably better.

2020-10-26 19:28 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +Optionally add some scripts to your top-level package.json.
```suggestion
Optionally, add some scripts to your top-level package.json.
```

2020-10-26 19:30 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +Your server should have a user for deploying the app with. It should be configured with a SSH key pair so you can easily SSH into it from your development environment. In this example this user is na
```suggestion
Your server should have a user for deployment, which should be configured with an SSH key pair providing access to your development environment. In this example, the user is named `deploy`.
```

2020-10-26 19:31 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +First, we need to create the directories for PM2.
```suggestion
First, we need to create the PM2 directories.
```

2020-10-26 19:32 UTC, thedavidprice commented on cookbook/Serverfull_Hosting.md
> +directory.
```suggestion
Your server directories are now set. However, the `.env` settings are not yet configured.
SSH into your server and create an `.env` file in the `current` subdirectory of the deploy directory.
```

2020-10-26 19:33 UTC, thedavidprice requested changes
See in-line comments; mostly small grammatical and a few structure related ideas.

2020-10-26 19:43 UTC, thedavidprice commented
Hi @njjkgeerts Thank you so much for this cookbook! It's definitely of high interest and value.

## Misc Edits
I went through the doc and suggested a lot of small edits. There were a few sentences that seemed to be split with a newline — I think I caught 'em all but do keep a lookout.

## Keywords: Nav Menu Item, Title, and Intro Paragraph
I don't have an answer to this, but I'm wondering about what keywords and descriptions we can add to help people find this Cookbook. "Serverfull" makes sense in the context of Serverless, but to the best of my knowledge, it's not a well-known term (yet). So when people are browsing the left column navigation docs, or using the site search, is there anything we can add to help others find this document and identify immediately with the topic. Some ideas:
- server hosting
- traditional or classic server architecture
- self-hosting Redwood
- hosting Redwood without serverless or docker containers

If there are some obvious ideas you want to run with, it's ok to do the following:
- have a unique Menu nave title
- and a unique Page title
- and/or include keywords and phrases in the introduction content

This isn't highest priority or blocking the PR. It's also something we can iterate on as we go. But if you have some immediate reactions and ideas, let try 'em out this round.

2020-10-29 10:24 UTC, njjkgeerts commented
@thedavidprice can you take a look at the updates? I agree with you that "serverfull" is not a common term. "Self-hosting Redwood" would be the best of your suggestions I think.

2020-10-29 13:46 UTC, peterp commented on cookbook/Serverfull_Hosting.md
> +> Caveat: the API seems to only work in fork mode in PM2, not cluster mode
Could you explain the difference or link to the docs where they explain the difference?

2020-10-29 14:56 UTC, cannikin commented
The opposite of “serverless” is obviously “servermore”, c’mon guys. 😁

2020-10-29 15:58 UTC, peterp commented
I thought it was serverplusplus

2020-10-30 04:06 UTC, thedavidprice commented
@njjkgeerts all the changes look great to me! Review approved on my end. Thanks 🚀

@peterp I'll let you take it from here.

2020-10-30 04:06 UTC, thedavidprice approved these changes

2020-10-30 04:10 UTC, thedavidprice commented on lib/build.js
> +      { pageBreakAtHeadingDepth: [1], file: './cookbook/Serverfull_Hosting.md' },
```suggestion
      { pageBreakAtHeadingDepth: [1], 
      file: './cookbook/Serverfull_Hosting.md',
      title: 'Self-hosting Redwood' },
```

2020-10-30 04:19 UTC, thedavidprice commented
Note: changed title of menu item. Could be just "Self-hosting". Open to suggestions otherwise.

<img width="241" alt="Screen Shot 2020-10-29 at 9 18 56 PM" src="https://user-images.githubusercontent.com/2951/97659485-5c0a6380-1a2c-11eb-8fe1-118bb834fd73.png">

2020-10-30 09:48 UTC, njjkgeerts commented on cookbook/Serverfull_Hosting.md
> +> Caveat: the API seems to only work in fork mode in PM2, not cluster mode
I also added the link in the document.
https://pm2.keymetrics.io/docs/usage/cluster-mode/

2020-10-30 14:43 UTC, thedavidprice commented on cookbook/Self-hosting_Redwood.md
> +# Self-hosting Redwood
```suggestion
# Self-hosting Redwood: Serverfull
```

For a term where it's unclear what the user is searching for, it's ok to have the Menu Title and the Page title be different (as long as they're intuitively related). The site search can pick up more keywords that way.

In this case, not sure if we _need_ to make the change I've suggested here, but I'm fine if we do. Or if there's a better title, please suggest!

And thank you for taking the time to think about keywords with me. It's important! If people can't find an article, then what's the point? 😉

2020-10-31 01:23 UTC, thedavidprice commented
All systems go! Thanks again @njjkgeerts 🚀

2020-10-31 01:23 UTC, merged