add Dutch translation
redwoodjs/redwoodjs.com pull request #50
Opened 2022-04-16 21:22 UTC by threes-was-taken

2022-04-17 04:08 UTC, jtoar commented
Thanks @threes-was-taken! @noire-munich ok if I tag you on this one?

2022-04-17 09:12 UTC, noire-munich commented
@jtoar sure!

2022-04-17 11:36 UTC, noire-munich requested changes
@threes-was-taken there are two changes from conflict solving, if you can have a look.
Work on the original PR is not complete yet, so we might bounce a bit more.

2022-04-17 11:36 UTC, noire-munich commented on web/src/locales/nl.json
> +    "misc": {
I've fixed the commits, `misc` doesn't exist anymore.

2022-04-17 11:36 UTC, noire-munich commented on web/src/locales/nl.json
> +    "social": {
I've fixed the commits, `misc` doesn't exist anymore. It was replaced by `announcements`.

2022-04-17 16:05 UTC, threes-was-taken commented on web/src/locales/nl.json
> +    "social": {
Do I remove the 'misc' key from the json or do I rename the key to ```announcements``` ?

2022-04-20 13:44 UTC, noire-munich commented on web/src/locales/nl.json
> +    "social": {
What you did is good :+1:

2023-05-11 12:04 UTC, closed without merging