Document the rw console command
redwoodjs/redwoodjs.com pull request #503
Opened 2021-01-06 20:47 UTC by jtoar

This PR adds a section about the console command being added in v0.22 to the CLI Commands doc (original PR for the console command: https://github.com/redwoodjs/redwood/pull/809).

2021-01-06 20:56 UTC, cannikin commented
Oh snap the console is going live in 0.22?? I think I'll add a section in the tutorial that uses it!

2021-01-07 17:49 UTC, thedavidprice requested changes

2021-01-07 17:49 UTC, thedavidprice commented on docs/cliCommands.md
> +Launch an interactive Redwood shell (experimental).
```suggestion
Launch an interactive Redwood shell (experimental):
- This has not yet been tested on Windows. 
- The Prisma Client must be generated _prior_ to running this command, e.g. `yarn rw db up`. This is a known issue.
```

2021-01-07 17:49 UTC, thedavidprice commented on docs/cliCommands.md
> +> ```
```suggestion
> ```
>
> Alternatively, on Mac or Linux you can pass the env var when you run the command:
> ```
> NODE_OPTIONS="--experimental-repl-await" yarn rw console
> ```
```

2021-01-07 17:49 UTC, thedavidprice approved these changes

2021-01-07 17:49 UTC, merged