#1622: Use PickerInline
redwoodjs/redwoodjs.com pull request #519
Opened 2021-01-14 04:38 UTC by vchoy

Addresses: https://github.com/redwoodjs/redwood/issues/1622

2021-01-14 06:57 UTC, Tobbe commented
Thanks for getting started on this @vchoy!

I noticed there are more instances of `<ReactFilestack>` in the document. Do you think you could update those as well?

2021-01-15 11:44 UTC, Tobbe requested changes

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +There's no reason to make the user click that button, let's just show the picker on the page when it loads by adding a couple of [pickerOptions](https://github.com/filestack/filestack-react#props). W
We don't actually add any `pickerOptions`, right? So I think you can reword this sentence.

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +  <div id="picker" style={{ marginTop: '2rem', height: '20rem' }}></div>
Is the `id` and the styles needed anymore? What does it look like with and without the styles?

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +	<PickerInline
Can you please see if you can fix the indentation here?

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +	<div
Can you please fix the indentation here?

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +			marginTop: '2rem',
Are all these styles still correct with the new inline picker?

2021-01-15 11:44 UTC, Tobbe commented on cookbook/File_Upload.md
> +        <PickerInline apikey={process.env.REDWOOD_ENV_FILESTACK_API_KEY} />
Aren't you missing a `<div>` as a child here? What does it look like if you render a `<PickerInline>` without that child?

2021-01-17 09:37 UTC, Tobbe commented on cookbook/File_Upload.md
> +We now have created a picker with all kinds of options, like picking a local file, providing a URL or even grabbing one from Facebook, Instagram or Google Drive. Not bad!
```suggestion
We have now created a picker with all kinds of options, like picking a local file, providing a URL or even grabbing a file from Facebook, Instagram or Google Drive. Not bad!
```

2021-01-17 09:37 UTC, Tobbe commented on cookbook/File_Upload.md
> +... And....you can even try uploading an image to make sure it works:
```suggestion
You can even try uploading an image to make sure it works:
```

2021-01-17 09:37 UTC, Tobbe commented on cookbook/File_Upload.md
> +For this we will need define a custom `<div>` and have it as a child of `<PickerInline>`. We'll also have the `<div>` display or hide itself (ie. the picker), if there exists a defined image url:
```suggestion
For this we will need to define a custom `<div>` and make it a child of `<PickerInline>`. We'll also have the `<div>` display or hide itself (i.e. the picker), if there exists a defined image url:
```

2021-01-17 09:43 UTC, Tobbe commented
This is starting to look really good @vchoy! I'm going to try to follow the updated cookbook recipe and see if any more changes are needed. Please remind me if you haven't heard back in a few days.

2021-01-18 12:25 UTC, Tobbe requested changes

2021-01-18 12:25 UTC, Tobbe commented on cookbook/File_Upload.md
>  ```javascript{14,18}
You need to update the highlighted lines by changing the numbers here (14,18 should be something else)
Also, try changing from javascript to jsx, see if that makes the highlighting look better

2021-01-18 12:25 UTC, Tobbe commented on cookbook/File_Upload.md
> +  ></div>
```suggestion
  <div style={{ display: url ? 'none' : 'block' }}></div>
```

2021-01-18 12:25 UTC, Tobbe commented on cookbook/File_Upload.md
> +  ></div>
I'm not seeing the file picker. Please fix the code so it's possible to upload an image

![image](https://user-images.githubusercontent.com/30793/104914081-e230a900-598e-11eb-988e-02239cf461f5.png)

2021-01-18 12:25 UTC, Tobbe commented on cookbook/File_Upload.md
>  {url && (
```jsx
        {url && (
          <div>
            <img src={url} style={{ display: 'block', marginTop: '2rem 0' }} />
            <button
              onClick={() => setUrl(null)}
              className="rw-button rw-button-blue"
            >
              Replace image
            </button>
          </div>
        )}
```

2021-01-18 12:25 UTC, Tobbe commented on cookbook/File_Upload.md
>  ```javascript{18-29}
these line numbers are wrong

2021-01-27 23:48 UTC, thedavidprice commented
Hi gents! Just checking in on this PR -- it's looking good but not yet complete, correct?

2021-01-28 07:13 UTC, Tobbe commented
@thedavidprice correct!

2021-09-17 23:32 UTC, merged