Updated code samples to reflect App.js instead of index.js
redwoodjs/redwoodjs.com pull request #643
Opened 2021-03-24 20:08 UTC by jacebenson

Hey, I went ahead and updated the comments on the snippets in the GoTure_Auth.md and authentication.md.  I also updated it in the customIndex.md, however that wasn't called out in the issue.

2021-03-24 20:08 UTC, jacebenson commented
This PR is for #634

2021-03-25 03:41 UTC, thedavidprice commented on cookbook/GoTrue_Auth.md
>  By specifying `goTrue` as the provider, Redwood automatically added the necessary GoTrue-JS config to our index.js. Let's open up `web/src/index.js` and inspect. You should see:
```suggestion
By specifying `goTrue` as the provider, Redwood automatically added the necessary GoTrue-JS config to our App.js. Let's open up `web/src/App.js` and inspect. You should see:
```

2021-03-25 03:43 UTC, thedavidprice commented on docs/customIndex.md
> +// web/src/App.js
```suggestion
// web/src/index.js
```

2021-03-25 03:48 UTC, thedavidprice requested changes
@jacebenson There were a couple of index.js --> App. js changes inline that were missed and I fixed.

The next change is to update the code in the App.js file itself. This is no longer relevant:
```js
ReactDOM.render(
  <FatalErrorBoundary page={FatalErrorPage}>
    <AuthProvider client={auth0} type="auth0">
      <RedwoodApolloProvider>
        <Routes />
      </RedwoodApolloProvider>
    </AuthProvider>
  </FatalErrorBoundary>,
  document.getElementById('redwood-app')
)
```

2021-03-25 05:35 UTC, jacebenson commented on cookbook/GoTrue_Auth.md
> -yarn redwood generate auth goTrue
When generating the code for the blocks before I copied/pasted this in and it didnt work.. So updated this to work.

2021-03-25 05:36 UTC, jacebenson commented on cookbook/GoTrue_Auth.md
> +yarn redwood setup auth goTrue
Corrected that here

2021-03-25 05:44 UTC, jacebenson commented
I did entirely miss the code blocks on the docs/authentication.md. I've since updated that file and the gotrue cookbook file to match the generators.

I went ahead and tested each command on a local nearly empty repo and copied the generated code where it applied.

2021-03-30 05:17 UTC, thedavidprice commented on docs/authentication.md
> +  redirect_uri: process.env.AUTH0_REDIRECT_URI,
great addition and comments!

2021-03-30 05:19 UTC, thedavidprice approved these changes

2021-03-30 05:20 UTC, thedavidprice commented
@jacebenson woah, I can tell you really spent some time digging into this one and getting the details right! Thank you so much. This was a greatly needed improvement.

2021-03-30 05:20 UTC, merged