Draft: Serverless function security considerations
redwoodjs/redwoodjs.com pull request #659
Opened 2021-04-04 10:30 UTC by dthyresson

Addresses Issue https://github.com/redwoodjs/redwood/issues/2014 in Redwood repo.

The function generator and template JSDoc will link to this documentation to help the develop understand how to better secure their function when deployed, if needed and appropriate, since many may not be aware that when deployed, the function is an open api endpoint that anyone can access.

2021-05-06 13:28 UTC, dthyresson commented
@dac09 and @Tobbe could I get a review as want Webhook docs in.

The GraphQL is going to be a placeholder for others to contribute best practices as noted on contributors call.

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +#### Visibility via Logging
```suggestion

#### Visibility via Logging
```

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +In addition to securing your serverless functions, you may consider logging, rate limiting, whitelisting as ways to protect your functions from abuse or misuse.
```suggestion
In addition to securing your serverless functions, you may consider logging, rate limiting and whitelisting as ways to protect your functions from abuse or misuse.
```

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +See [Logger](/docs/logger) in the RedwoodJS for more information about how to setup and use logging services.
```suggestion
See [Logger](/docs/logger) in the RedwoodJS docs for more information about how to setup and use logging services.
```

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +Currently, RedwoodJS does not offer rate limiting in the framework, but your deployment target infrastructure may. This is a feature redwoodJS will investigate for future releases.
```suggestion
Currently, RedwoodJS does not offer rate limiting in the framework, but your deployment target infrastructure may. This is a feature RedwoodJS will investigate for future releases.
```

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +Currently, RedwoodJS does not offer rate limiting in the framework, but your deployment target infrastructure may. This is a feature redwoodJS will investigate for future releases.
Do we want to make promises like these about the future? :)

2021-05-06 14:05 UTC, Tobbe commented on docs/serverlessFunctions.md
> +#### IP Address Whitelisting
```suggestion

#### IP Address Whitelisting
```

2021-05-06 14:19 UTC, dthyresson commented on docs/graphql.md
> +> Please come back soon where we will document more best practices when securing GraphQL as RedwoodJS reaches a v1.0 release candidate.
I agree. I was struggling to say "coming soon". I'll reword and seen if maybe @thedavidprice can improve.

2021-05-06 14:21 UTC, dthyresson commented on docs/serverlessFunctions.md
> +Currently, RedwoodJS does not offer rate limiting in the framework, but your deployment target infrastructure may. This is a feature redwoodJS will investigate for future releases.
Also a question for Tom or @thedavidprice - I know we have discussed it informally but have not formed an opinion of the best solution. Perhaps can make less absolute and open ended.

I did want to raise the topic of rate limiting so people are aware of the concept.

2021-05-09 14:15 UTC, dthyresson commented
@thedavidprice Would you have time to review? There are a few RW positions taken than need an ok. Thanks.

2021-05-11 23:52 UTC, jtoar requested changes
More to come! Didn't touch the Webhook doc at all yet; in general, tried to be a little less formal (relaxing RedwoodJS Framework to Redwood, things like that). Mostly just edits, no new content, but happy to collaborate on that / once I get a better feel for the code

2021-05-11 23:52 UTC, jtoar commented on docs/graphql.md
> +> Please come back soon where we will document more best practices when securing GraphQL as RedwoodJS reaches a v1.0 release candidate.
- there doesn't seem like there's enough here for two paragraphs; we could put it all in aside if you want
```suggestion
We'll document more GraphQL security best practices as Redwood reaches a v1.0 release candidate, but note that Redwood already bakes in some when deploying GraphQL to production, such as disabling the GraphQL Playground.
```

2021-05-11 23:52 UTC, jtoar commented on docs/security.md
> +When deployed, a custom [serverless function](/docs/serverless-functions) is an open API endpoint and is your responsibility to secure appropriately.
It's tough; the api side I feel like should be lowercase, unless we're going to capitalize WEB. But API as just the word it is without any Redwood connotations should definitely be capitalized, and that's how it's being used here I think

2021-05-11 23:52 UTC, jtoar commented on docs/security.md
> +That means that that anyone can access your function and perform any tasks it's asked to do. In many cases, this is completely appropriate and desired behavior. But, there are often times you need to
- combine paragraphs
- typos
- improve flow
```suggestion
When deployed, a [serverless function](/docs/serverless-functions) is an open API endpoint. That means anyone can access it and perform any tasks it's asked to do. In many cases, this is completely appropriate and desired behavior. But there are often times you need to restrict access to a function, and Redwood can help you do that using a [variety of methods and approaches](/docs/serverless-functions#security-considerations).
```

2021-05-11 23:52 UTC, jtoar commented on docs/security.md
> +For details on how to keep your incoming webhooks secure and how to sign your outgoing webhooks, please see: [Webhooks](/docs/webhooks) section in the RedwoodJS documentation.
```suggestion
For details on how to keep your incoming webhooks secure and how to sign your outgoing webhooks, please see [Webhooks](/docs/webhooks).
```

2021-05-11 23:52 UTC, jtoar commented on docs/security.md
> +They are a form of messaging and automation allows web applications to communicate with each other and send real-time data from one application to another whenever a given event occurs.
- one paragraph
- tighten a bit in general
- not mutually exclusive with Tobbe's!
```suggestion
[Webhooks](/docs/webhooks) are how third-party services notify your app when an event of interest happens. 
They're a form of messaging and automation that allows web apps to communicate with each other and send real-time data whenever a given event occurs.
```

2021-05-12 04:21 UTC, jtoar requested changes
Here's another round. Still need to edit a bit more, but don't want to overwhelm / I'm dulling a bit. Main edits to make going forward are structural, combining paragraphs where possible and making sure there's transitions between them

2021-05-12 17:51 UTC, dthyresson commented
@thedavidprice ready for final review.

2021-05-13 10:55 UTC, dac09 commented
Hey @dthyresson lock file conflict 🙈

2021-05-13 11:15 UTC, dthyresson commented
> Hey @dthyresson lock file conflict 🙈

Ok I'll have a look after @thedavidprice reviews and edits the general sections and validates the RW messaging is ok.

2021-05-13 21:01 UTC, thedavidprice commented on docs/graphql.md
> +We'll document more GraphQL security best practices as Redwood reaches a `v1.0` release candidate, but note that Redwood already has some baked-in when deploying GraphQL to production, such as disabl
```suggestion
We'll document more GraphQL security best practices as Redwood reaches a `v1.0` release candidate. For now, know that Redwood already has some baked-in best practices; for example, when deploying GraphQL to production, GraphQL Playground is automatically disabled. 
```

2021-05-13 21:40 UTC, thedavidprice commented on docs/graphql.md
> +Some of the biggest security improvements we'll be making revolve around Services (which are intimately linked to GraphQL since they're wrapped into your resolvers), and  for `v1.0` we plan on making
```suggestion
Some of the biggest security improvements we'll be making revolve around Services (which are intimately linked to GraphQL since they're wrapped into your resolvers). For `v1.0` we plan to make all of your resolvers secure by default. You can even opt into this behavior now—see the [Secure Services](/docs/services) section.
```

2021-05-13 21:46 UTC, thedavidprice commented on docs/security.md
> +> While Redwood offers the tools, practices, and information to keep your application secure, it remains your responsibility to put these in place. Proper password, token, and key protection using di
```suggestion
> ⚠️ Security is Your Responsibility
> While Redwood offers the tools, practices, and information to keep your application secure, it remains your responsibility to put these in place. Proper password, token, and key protection using disciplined communication, password management systems, and environment management services like [Doppler](https://www.doppler.com) are strongly encouraged.
```

2021-05-13 21:50 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +When deployed, a custom serverless function is an open API endpoint and is your responsibility to secure appropriately.
```suggestion
When deployed, **a custom serverless function is an open API endpoint and is your responsibility to secure appropriately**. 🔐
```

2021-05-13 21:51 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +That means that that anyone can access your function and perform any tasks it's asked to do. In many cases, this is completely appropriate and desired behavior.
```suggestion
That means _anyone_ can access your function and perform any tasks it's asked to do. In many cases, this is completely appropriate and desired behavior. 
```

2021-05-13 21:51 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +> disclaimer
```suggestion
```

2021-05-13 21:53 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +Logging in production -- and monitoring for suspicious activity, unknown IP addresses, errors, etc -- can be a critical part of keeping your serverless functions and your application safe.
```suggestion
Logging in production — and monitoring for suspicious activity, unknown IP addresses, errors, etc. — can be a critical part of keeping your serverless functions and your application safe.
```

2021-05-13 21:54 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +For more information about Rate Limiting in Node, consider:
```suggestion
For more information about Rate Limiting in Node.js, consider:
```

2021-05-13 21:56 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +Rate limiting (or throttling) how often a function executes by a particular IP addresses or user account is a common way of stemming api abuse.
```suggestion
Rate limiting (or throttling) how often a function executes by a particular IP addresses or user account is a common way of stemming api abuse (for example, a Denial-of-Service attack).
```

2021-05-13 21:57 UTC, thedavidprice commented on docs/serverlessFunctions.md
> +* Denial-of-Service. Example, if query db, consume all connections.
```suggestion
```

2021-05-13 22:02 UTC, thedavidprice commented on docs/webhooks.md
> +They are a form of messaging and automation allows web applications to communicate with each other and send real-time data from one application to another whenever a given event occurs.
```suggestion
They are a form of messaging and automation allowing distinct web applications to communicate with each other and send real-time data from one application to another whenever a given event occurs.
```

2021-05-13 22:06 UTC, thedavidprice commented on docs/webhooks.md
> +* [Orbit](https://docs.orbit.love/docs/webhooks)
```suggestion
* [Orbit Webhook Doc](https://docs.orbit.love/docs/webhooks)
```

2021-05-13 22:20 UTC, dthyresson commented on docs/webhooks.md
> +  await got.put(
Yes, it should be post. Correcting.

2021-05-13 22:31 UTC, dthyresson commented on docs/webhooks.md
> +They are a form of messaging and automation allows web applications to communicate with each other and send real-time data from one application to another whenever a given event occurs.
I am making this intro a bit punchier and salesy.

2021-05-13 22:36 UTC, dthyresson commented on docs/webhooks.md
> +Since each of these webhooks will call a function endpoint in your RedwoodJS api, you need to ensure that these run **only when they should**. That means you need to:
Added the intro

2021-05-13 23:02 UTC, thedavidprice approved these changes

2021-05-13 23:16 UTC, merged