Updated forms doc to match redwood pr#2167.
redwoodjs/redwoodjs.com pull request #660
Opened 2021-04-04 22:49 UTC by cjreimer

This change adds some clarification into the docs regarding transformValue, with respect to the changes in pr redwoodjs/redwood#2167

@Tobbe flagged for you as you have helped me in the pr review.  Thanks!

2021-04-05 08:04 UTC, Tobbe requested changes

2021-04-05 08:04 UTC, Tobbe commented on docs/form.md
> +```
```suggestion
```

2021-04-05 08:04 UTC, Tobbe commented on docs/form.md
> +If the production environment is set to `development` or `test`, it will also issue a console warning upon a failed transformation.  It is recommended to set up your field validation to avoid cases o
```suggestion
If the `NODE_ENV` environment variable is set to `development` or `test`, it will also issue a console warning upon a failed transformation.  It is recommended to set up your field validation to avoid cases of failed transformation.  In the specific case of the example above, it would be recommended to add a `validation={{ required: true }}` to the code as per the below.
```

2021-04-05 08:04 UTC, Tobbe commented on docs/form.md
> +Caveat:  JSON validation will not applied if a custom validation function, such as `fcn` is provided via the prop as follows: `validation={{ validate: fcn }}`
```suggestion
Caveat:  JSON validation will not be applied if a custom validation function, such as `fcn` is provided via the prop as follows: `validation={{ validate: fcn }}`
```

2021-04-05 16:01 UTC, Tobbe approved these changes

2021-04-05 16:02 UTC, Tobbe commented
Thanks for updating the docs Curtis. We'll merge this when we release the next version of RW

2021-04-06 07:28 UTC, thedavidprice commented
✅ on the list!

2021-04-09 05:02 UTC, merged