Update typescript docs
redwoodjs/redwoodjs.com pull request #678
Opened 2021-04-27 11:35 UTC by dac09

Updates docs for setting up typescript - no longer manual! 🎊

2021-04-27 16:22 UTC, thedavidprice requested changes
Looking good! A few minor edits to handle.

2021-04-27 16:22 UTC, thedavidprice commented on docs/cliCommands.md
>  This command runs the steps to both build your project _and_ deploy it to AWS.
Without the two spaces, this collapses from a header into the first sentence. I think that would be fine if you added a ":", e.g. `Netlify, Vercel, and Render:`

Here's what it looks like with this edit:
<img width="680" alt="Screen Shot 2021-04-27 at 9 18 00 AM" src="https://user-images.githubusercontent.com/2951/116276754-a9486300-a739-11eb-85e8-c67af938378a.png">

2021-04-27 16:22 UTC, thedavidprice commented on docs/typescript.md
> +2. You can call this folder whatever you like ofcourse, just add the same folder to your includes
```suggestion
2. You can call this folder whatever you like, of course, just add the same folder to your includes
```

2021-04-27 16:22 UTC, thedavidprice commented on docs/typescript.md
> +
```suggestion
```

2021-04-27 16:27 UTC, dac09 commented on docs/cliCommands.md
>  This command runs the steps to both build your project _and_ deploy it to AWS.
Yeah it was the auto formatter I think. Nice catch, I'll add a <br>

2021-04-27 16:31 UTC, dac09 commented on docs/cliCommands.md
>  This command runs the steps to both build your project _and_ deploy it to AWS.
Done ✅

2021-04-28 18:30 UTC, thedavidprice approved these changes

2021-04-28 18:30 UTC, merged