added documentation for testing forms using @testing-library/user-event
redwoodjs/redwoodjs.com pull request #683
Opened 2021-05-05 02:16 UTC by realStandal

It was recommended to me by @cannikin to include [my forum post on testing forms using `@testing-library/user-event`](https://community.redwoodjs.com/t/testing-forms-using-testing-library-user-event/2058) in the main Redwood docs, this is that.

This documentation is different than my original post. In this, I'm using the `@redwoodjs/forms` package (as opposed to `react-hook-forms` directly) and everything is written in JavaScript. I've also left out the Storybook portion.

As I said on my post, I was going to make an issue to include `@testing-library/user-event` in the main `@redwoodjs/testing` package. I can still do that before this is merged (to remove the need to install it explicitly). I can take on the issue as well.

2021-05-12 14:13 UTC, jtoar requested changes
@realStandal thanks so much for this! I made a few edits that I'd like your feedback on whenever you have time. the main thing I want to get clear is if we should talk about the user-event library in code as userEvent or just user

2021-05-14 15:58 UTC, thedavidprice commented
@realStandal thanks for this! Just making sure you saw the comments from @jtoar's review.

2021-05-14 23:11 UTC, realStandal commented on docs/testing.md
> +To test our forms, we can make use of of the [`@testing-library/user-event`](testing-library/user-event) library.
I used the [GitHub repository](https://github.com/testing-library/user-event), but I like this link better as it has a dual-function of exposing anyone who follows it to a wealth of other testing libraries and resources.

That would probably explain the difference between my use of `user` and your expectation/suggestion of `userEvent`.

2021-05-14 23:18 UTC, realStandal commented on docs/testing.md
> +> `user-event` tries to simulate the real events that would happen in the browser as the user interacts with it. For example `userEvent.click(checkbox)` would change the state of the checkbox.
The first sentence are my words; the second, blockquote, is quoted from the [`user-event` GitHub repository](https://github.com/testing-library/user-event#the-solution). I'm not against rewording it to put it more in the context of a Redwood application.

2021-05-14 23:19 UTC, realStandal commented on docs/testing.md
> +3) Provide an `onSubmit` prop to our "renders successfully" test.
Decapitalize "Import" on the second bullet.

2021-05-15 00:15 UTC, realStandal commented
> @realStandal thanks so much for this! I made a few edits that I'd like your feedback on whenever you have time. the main thing I want to get clear is if we should talk about the user-event library in code as userEvent or just user

I'm impartial either way. I thought I got `user` from the library's GitHub readme, but it must have just been me when I wrote the test. So `userEvent` would be the way to go to stay consistent.

2021-05-15 00:44 UTC, jtoar commented on docs/testing.md
> +3) Provide an `onSubmit` prop to our "renders successfully" test.
Thanks just made that change

2021-05-15 00:58 UTC, jtoar commented on docs/testing.md
> +> `user-event` tries to simulate the real events that would happen in the browser as the user interacts with it. For example `userEvent.click(checkbox)` would change the state of the checkbox.
Ah gotcha we'll definitely want to reword it more if we're taking it out of the quoted context then

2021-05-15 01:08 UTC, jtoar requested changes
@realStandal identified the places where we should change `user` to `userEvent` and suggested some new copy for the blockquote

2021-05-15 01:08 UTC, jtoar commented on docs/testing.md
> +    await waitFor(() => user.click(submitButton))
```suggestion
    await waitFor(() => userEvent.type(nameField, name))
    await waitFor(() => userEvent.type(nicknameField, nickname))
    await waitFor(() => userEvent.click(submitButton))
```

2021-05-15 01:08 UTC, jtoar commented on docs/testing.md
> +> `user-event` tries to simulate the real events that would happen in the browser as the user interacts with it. For example `userEvent.click(checkbox)` would change the state of the checkbox.
- how's this new copy sound?
```suggestion
To test our forms, we can make use of of the [`@testing-library/user-event`](https://testing-library.com/docs/ecosystem-user-event/) library which helps us approximate the the events that would actually happen in the browser if a real user were interacting with our forms. For example, calling `userEvent.click(checkbox)` toggles a checkbox as if a user had clicked it.
```

2021-05-15 01:51 UTC, realStandal commented
Thank you for your help @jtoar! I'm going to try and learn to suggest-and-edit or whatever it's technically called you've been doing.

Or is that locked to only reviewers? (I think it is, it greys-out the "Suggest a change" option I believe you're using)

2021-05-15 02:13 UTC, jtoar commented
@realStandal my pleasure, thank you for contributing! And it's definitely a handy feature. I think you should be able to do it too, here's a video showing how it's done: https://s.tape.sh/vo9w2p6x

2021-05-15 04:42 UTC, merged

2021-05-15 06:08 UTC, realStandal commented
> @realStandal my pleasure, thank you for contributing! And it's definitely a handy feature. I think you should be able to do it too, here's a video showing how it's done: https://s.tape.sh/zKF00IwT

Not what I was looking at, thank you very much! Happy to help 🚀