Documents esbuild and apiproxy opts
redwoodjs/redwoodjs.com pull request #703
Opened 2021-05-25 07:16 UTC by pdjota

This updates the docs with current options available, including a new `esbuild` option which should be merged by https://github.com/redwoodjs/redwood/pull/2564

2021-05-25 07:17 UTC, pdjota commented
@thedavidprice wrt esbuild option

2021-05-25 17:35 UTC, jtoar requested changes
@ pdjota Code + docs = the total package :rocket: Thanks! Just a few comments:

2021-05-25 17:35 UTC, jtoar commented on docs/appConfiguration.md
> +This section includes features that are *not stable* and maybe removed in future versions.
Needs a space, not sure why; something about verbs vs. adverbs 🤷
```suggestion
This section includes features that are *not stable* and may be removed in future versions.
```

2021-05-25 17:35 UTC, jtoar commented on docs/appConfiguration.md
> +| `a11y`                        | Enable webpack's fast refresh      | true                    | `development` |
I messed up the nice table formatting, but this one needs updating:

```suggestion
| `a11y`                        | Enable storybook addon-a11y and eslint-plugin-jsx-a11y  | true                    | `development` |
```

2021-05-25 17:35 UTC, jtoar commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
Whoa—you're right, in the framework, it _is_ prisma! We definitely need to update this on the framework side

2021-05-25 22:17 UTC, thedavidprice commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
Yikes. @jtoar are you on this one? If so, let's revert this change and just fix the path in Framework. 

Great catch!

2021-05-26 07:13 UTC, pdjota commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
sorry, I'm not following, what do I need to change?

2021-05-26 17:25 UTC, thedavidprice commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
The correct config _should be:_
- `schemaPath: './api/db/schema.prisma',`

It is _incorrect_ in the Framework file `config.ts` (🐛Yikes!)

**Next Steps:**
1. patch the value in `config.ts`
2. Doc should be `schemaPath: './api/db/schema.prisma'`

Let me know if you'd like to open a PR for step 1. I can do it otherwise.

2021-05-27 09:44 UTC, pdjota commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
Ok, I will try to address on w.e. thanks!

2021-05-27 17:53 UTC, thedavidprice commented on docs/appConfiguration.md
> +    schemaPath: './api/prisma/schema.prisma',
Created an issue: https://github.com/redwoodjs/redwood/issues/2644

2021-06-04 21:23 UTC, merged