Documentation for rw test's new --db-push flag
redwoodjs/redwoodjs.com pull request #707
Opened 2021-05-28 22:34 UTC by pachoclo

Updates the docs to include the work done in https://github.com/redwoodjs/redwood/pull/2642.

Screenshot: 
<img width="688" alt="Screen Shot 2021-05-28 at 6 28 36 PM" src="https://user-images.githubusercontent.com/3608140/120047646-18d49b00-bfe3-11eb-82cb-a182f29cceef.png">

---
cc @dac09

2021-05-28 23:37 UTC, jtoar requested changes
@pachoclo thanks for updating the docs as well, really appreciate it! 👏  I made a few edits to the description.

Is it possible to only include the change you made to the cliCommands doc? Right now your PR includes changes to a few other files, like the `yarn.lock`.

Let me know if you need any help doing this!

2021-05-28 23:37 UTC, jtoar commented on docs/cliCommands.md
> +| `--db-push`         | Syncs the test database with your Prisma schema without requiring a migration. It creates a test database if it doesn't already exist [default: true]. Note that this flag is i
Just a few edits:
```suggestion
| `--db-push`         | Syncs the test database with your Prisma schema without requiring a migration. It creates a test database if it doesn't already exist [default: true]. This flag is ignored if your project doesn't have an `api` side. [👉 More details](https://redwoodjs.com/docs/cli-commands#prisma-db-push). |
```

2021-05-29 20:03 UTC, pachoclo commented
> Is it possible to only include the change you made to the cliCommands doc? Right now your PR includes changes to a few other files, like the `yarn.lock`.

Sure sure. I was hesitant to commit them--I should have asked first :)

2021-06-15 12:00 UTC, dac09 approved these changes
HODL till next release. Thanks again @pachoclo

2021-06-18 01:11 UTC, merged