Adds link to the Guild's envelop docs with info for ac secure GraphQL api
redwoodjs/redwoodjs.com pull request #761
Opened 2021-08-01 10:55 UTC by dthyresson

Envelop has documentation with best practices for securing your GraphQL API.

This PR links to it for further reading.

2021-08-10 11:26 UTC, dac09 requested changes
Link is now 404-ing :)

2021-08-11 23:52 UTC, thedavidprice commented on docs/graphql.md
> +For more information about how to keep your GraphQL API secure, please read [Securing your GraphQL API](https://www.envelop.dev/docs/guides/) from [the Guild](https://the-guild.dev).
```suggestion
For more information about how to keep your GraphQL API secure, please read [Securing your GraphQL API](https://www.envelop.dev/docs/guides/securing-your-graphql-api) from [the Guild](https://the-guild.dev).
```

Looks like you'll need to use this link @dthyresson 

Go ahead an merge once you're happy with it.

2021-08-17 10:17 UTC, dac09 commented
Hey @dthyresson - so I did a quick skim of the guid docs. They're very solid docs - but they seem to go in a different direction to how we do auth in Redwood. Worth reviewing again before merge!

2021-08-17 22:44 UTC, dthyresson commented
Yeah, on second thought this muddies the issue. I am closing without merging.

2021-08-17 22:44 UTC, closed without merging