Documents RedwoodApolloProvider's `graphQLClientConfig` prop
redwoodjs/redwoodjs.com pull request #778
Opened 2021-08-20 11:44 UTC by zackdotcomputer

Follow up for [my PR adding cache config support](redwoodjs/redwood#3145), this adds documentation for the `graphQLClientConfig` prop on `RedwoodApolloProvider` and how to use it to configure your cache's type policy.

2021-08-28 00:00 UTC, jtoar requested changes
Hey @zackdotcomputer, awesome job on the docs! I added a few suggestions, mostly just for clarity/brevity—let me know what you think. 

Also, if you're an Apollo Client wizard, I'd love to pair on some more docs and/or best practices for modifying the cache.

2021-08-28 00:00 UTC, jtoar commented on docs/graphql.md
> +For example, if you had a query named `search` that supports [Apollo's offset pagination](https://www.apollographql.com/docs/react/pagination/core-api/), you could add support for this on your site b
- tense, tighten
```suggestion
For example, if you have a query named `search` that supports [Apollo's offset pagination](https://www.apollographql.com/docs/react/pagination/core-api/), you could enable it by specifying:
```

2021-08-28 00:00 UTC, jtoar commented on docs/graphql.md
> +Additionally, depending on your use case, you may want to customize the cache's configuration. For example, you may need to specify a type policy to change the key by which a model is cached or to en
- tighten
```suggestion
Depending on your use case, you may want to configure `InMemoryCache`. For example, you may need to specify a type policy to change the key by which a model is cached or to enable pagination on a query. [This article from Apollo](https://www.apollographql.com/docs/react/caching/cache-configuration/) explains in further detail why and how you might want to do this.
```

2021-08-28 00:00 UTC, jtoar commented on docs/graphql.md
> +To configure the cache when it is created use the `cacheConfig` key on the `graphQLClientConfig` object. Any value you pass to this key will be passed directly to the `InMemoryCache` instance when it
- add comma, tense, contractions, tighten
```suggestion
To configure the cache when it's created, use the `cacheConfig` property on `graphQLClientConfig`. Any value you pass is passed directly to `InMemoryCache` when it's created.
```

2021-08-28 00:00 UTC, jtoar commented on docs/graphql.md
> +By default, `RedwoodApolloProvider` configures an `ApolloClient` instance with an `InMemoryCache` to store responses from the GraphQL API and an `authMiddleware` to sign requests to the API for use w
- enumerate to make things a little clearer, tigthen
```suggestion
By default, `RedwoodApolloProvider` configures an `ApolloClient` instance with 1) a default instance of `InMemoryCache` to cache responses from the GraphQL API and 2) an `authMiddleware` to sign API requests for use with [Redwood's built-in auth](https://redwoodjs.com/docs/authentication). Beyond the `cache` and `link` params, which are used to set up that functionality, you can specify additional params to be passed to `ApolloClient` using the `graphQLClientConfig` prop. The full list of available configuration options for the client are [documented here on Apollo's site](https://www.apollographql.com/docs/react/api/core/ApolloClient/#options).
```

2021-09-07 10:51 UTC, zackdotcomputer commented
Just a ping to say I'm not abandoning this - work has been very busy the last couple weeks leading up to a launch. I should have time to revisit this and incorporate your suggestions this weekend, @jtoar. Sorry for the delay.

2021-09-07 20:04 UTC, jtoar commented
@zackdotcomputer No worries at all, thanks for the update. And no pressure—I can totally take this one to the finish line if needed, just let me know. Appreciate the work done so far!

2021-09-12 16:43 UTC, zackdotcomputer commented
Once I had time to read through them, those were an easy "approved in 30 seconds" group of suggestions. Thanks for them.

And I wouldn't say I'm an Apollo wizard, more an enthusiast at this point 😅 but learning quickly since it pairs well with the tech I am actually an expert in.

2021-09-17 00:29 UTC, thedavidprice commented
nudging @jtoar here

2021-09-17 00:32 UTC, jtoar approved these changes

2021-09-17 00:36 UTC, merged