Storybook: added documentation for `storybook.manager.js`
redwoodjs/redwoodjs.com pull request #885
Opened 2021-11-20 03:31 UTC by realStandal

Updates [the Storybook docs](https://redwoodjs.com/docs/storybook), adding information on how to theme Storybook.

It also updates the existing configuration-introduction to include details about `storybook.manager.js`.

2021-11-20 03:47 UTC, realStandal commented
I guess it added a lot of ESLint changes as-well, should these stay, or?

2021-11-23 19:14 UTC, jtoar commented
@realStandal Thanks for doing the docs too! I'll have a look now. And don't worry about the linting

2021-11-23 19:38 UTC, jtoar requested changes
@realStandal awesome job! Thanks for keeping the same structure of the document and just extending it. Left you a few comments

2021-11-23 19:38 UTC, jtoar commented on docs/storybook.md
> +`storybook.config.js` configures Storybook's server, `storybook.manager.js` Storybook's UI, while `storybook.preview.js` configures the way stories render.
Make this a parallel construct:
```suggestion
`storybook.config.js` configures Storybook's server, `storybook.manager.js` configures Storybook's UI, and `storybook.preview.js` configures the way stories render.
```

2021-11-23 19:38 UTC, jtoar commented on docs/storybook.md
> +> The easiest way to do so will be when starting Storybook:
Change tone:
```suggestion
> Note that some of the changes you make to Storybook's UI require refreshing its cache.
> The easiest way to do so is when starting Storybook:
```

2021-11-23 19:38 UTC, jtoar commented on docs/storybook.md
> +> `yarn rw storybook --no-manager-cache`
A full-on code block will look nicer:
```suggestion
> ```
> yarn rw storybook --no-manager-cache
> ```
```

2021-11-23 19:38 UTC, jtoar commented on docs/storybook.md
> +[Theming Storybook's UI](https://storybook.js.org/docs/react/configure/theming) can be accompished by installing two packages, and making a few changes to Redwood's inital configuration.
Change from passive to active:
```suggestion
You can [theme Storybook's UI](https://storybook.js.org/docs/react/configure/theming) by installing two packages and making a few changes to Redwood's initial configuration.
```

2021-11-23 19:38 UTC, jtoar commented on docs/storybook.md
> +You may also want to export your theme to [re-use it with Storybook Docs](https://storybook.js.org/docs/react/configure/theming#theming-docs).
Let's make this one paragraph:
```suggestion
Check out [Storybook's theming quickstart](https://storybook.js.org/docs/react/configure/theming#create-a-theme-quickstart) for a guide on creating your own theme. You may also want to export your theme to [re-use it with Storybook Docs](https://storybook.js.org/docs/react/configure/theming#theming-docs).
```

2021-11-23 19:52 UTC, realStandal commented on docs/storybook.md
> +> `yarn rw storybook --no-manager-cache`
Will that play well with the fact the code-block will be inside of a blockquote?

2021-11-23 19:55 UTC, realStandal commented on docs/storybook.md
> +> `yarn rw storybook --no-manager-cache`
I guess I can just commit it and we can see in the preview?

2021-11-23 19:57 UTC, realStandal commented
Thank you @jtoar.

Just want to make sure the code-block in the blockquote is going to render okay, unless you know it will - in which case, she's ready :)

2021-11-23 20:00 UTC, jtoar commented
@realStandal Looking good!

<img width="691" alt="image" src="https://user-images.githubusercontent.com/32992335/143095226-37a565d5-dbdc-4412-b9d1-9dbd085f1573.png">

2021-11-23 20:00 UTC, jtoar approved these changes

2021-11-30 05:08 UTC, merged