Document why currentUser might be null after mocking
redwoodjs/redwoodjs.com pull request #927
Opened 2021-12-21 19:11 UTC by callingmedic911

Closes https://github.com/redwoodjs/redwood/issues/3912.

2021-12-21 23:29 UTC, cannikin requested changes

2021-12-21 23:29 UTC, cannikin commented on docs/testing.md
> +Note that even after setting with `mockCurrentUser()` the initial render of the component might have still have null `currentUser` from `useAuth()`. It is updated after `getCurrentUser()` with mock d
I wanted to just reword this a bit:

```suggestion
Note that even after setting with `mockCurrentUser()`, the initial render of the component might return `null` for the `currentUser` that you destructured from `useAuth()`. Once `getCurrentUser()` is executed, `currentUser` will be updated with the expected data.
```

2022-01-06 18:26 UTC, cannikin commented
What do you think about this update @jtoar? I'm still not 100% sure I understand the problem: I haven't run into this issue, but everyone else says it's potentially confusing!

2022-01-06 21:14 UTC, jtoar commented
@cannikin I agree that it seems like if you use `waitFor` or an async matcher (not sure if that's the right term—`queryByRole`, `findByText`, etc), this just takes care of itself. 

But maybe where the confusion occurs is: it doesn't seem like we say that `waitFor` and/or an async matcher is necessary and if it is (seems like it is), why. Right now we say we use `waitFor` because `queryByRole` isn't async, but we don't explain why being async matters. So maybe I can work @callingmedic911's new paragraph into the previous one or just add a callout that says "hey, we're using waitFor and/or an async matcher because we need to wait for an update because currentUser is actually `null` in the first render..."

2022-01-07 00:39 UTC, jtoar commented on docs/testing.md
> +Note that even after setting with `mockCurrentUser()`, the initial render of the component might return `null` for the `currentUser` that you destructured from `useAuth()`. Once `getCurrentUser()` is
@callingmedic911 what do you think of this?
```suggestion
The async behavior here is important. Even after setting the user with `mockCurrentUser()`, `currentUser` may be `null` during the initial render because it's being resolved. Waiting for a render update before passing/failing the exception gives the resolver a chance to execute and populate `currentUser`.
```

2022-01-07 19:26 UTC, callingmedic911 commented on docs/testing.md
> +Note that even after setting with `mockCurrentUser()`, the initial render of the component might return `null` for the `currentUser` that you destructured from `useAuth()`. Once `getCurrentUser()` is
This is way better! Thanks, @jtoar. Why is so hard for me to write I'm thinking. Hah!

2022-01-07 20:11 UTC, jtoar approved these changes

2022-01-13 00:10 UTC, merged