WIP - Draft - docs: How to authenticate in serverless functions
redwoodjs/redwoodjs.com pull request #928
Opened 2021-12-22 01:35 UTC by dthyresson

WIP - How to authenticate in serverless functions

@todo

2022-01-06 20:17 UTC, jtoar requested changes
Hey @dthyresson I edited some of the copy and have a few questions I've left as comments.

One thing that wasn't obvious to me: after wrapping a serverless function handler in `useRequireAuth`, are you supposed to use `requireAuth` in the body of the function? Or is it already setup to require auth?

2022-01-06 20:17 UTC, jtoar commented on docs/serverlessFunctions.md
> +> If you need to protect an endpoint via authentication that isn't user-based, you should consider using [Webhooks](/webhooks) with a signed payload and verifier.
@dthyresson previously this sentence was: "In addition, if you need to protect an endpoint that does not require not user-based authentication, you should consider using [Webhooks](/webhooks) with a signed payload and verifier."

That had too many negatives (does not require not...) so I edited it, but did I keep the logic the same?

2022-01-18 14:56 UTC, dthyresson commented
> fter wrapping a serverless function handler in `useRequireAuth`, are you supposed to use `requireAuth` in the body of the function? Or is it already setup to require auth?

Good point. It means you can use the `auth` functions like `isAuthenticated()` or `hasRole()` or `requireAuth()` ... it lets you "use" any of the require auth-ivied functions.

2022-01-30 18:58 UTC, jtoar approved these changes

2022-01-30 19:00 UTC, merged