Docs: Document Custom Fastify Server configuration serttings
redwoodjs/redwoodjs.com pull request #932
Opened 2021-12-23 19:01 UTC by dthyresson

Fixes: https://github.com/redwoodjs/redwoodjs.com/issues/926

2021-12-24 01:56 UTC, dac09 commented on docs/appConfiguration.md
> +  apiUrl = "${API_URL}/.redwood/functions"
Think this change isn't correct! The one before was correct :)

2021-12-24 12:26 UTC, dthyresson commented on docs/appConfiguration.md
> +  apiUrl = "${API_URL}/.redwood/functions"
```suggestion
  apiUrl = "${API_URL:/.redwood/functions}"
```

2021-12-30 18:50 UTC, dac09 requested changes

2021-12-30 18:50 UTC, dac09 commented on docs/appConfiguration.md
> +| `serverConfig` | Path to the `server.config.js` file | `'./api'`     | `both`        |
I think the default is `./api/server.config.js`

2021-12-30 18:50 UTC, dac09 commented on docs/appConfiguration.md
> +/**
Do you think we could remove this comment block? Repeated above I believe

2021-12-30 18:50 UTC, dac09 commented on docs/appConfiguration.md
> +  serverConfig = = "./api/${DEPLOY_ENVIRONMENT}-server.config.s"
```suggestion
  serverConfig = = "./api/${DEPLOY_ENVIRONMENT}-server.config.js"
```

2022-01-04 18:15 UTC, dac09 commented
@dthyresson mind resolving the conflicts?

2022-01-04 18:16 UTC, dac09 approved these changes

2022-01-04 18:17 UTC, dac09 commented on docs/appConfiguration.md
> +/**
I think you may have resolved this accidentally (im ok if you don't want to remove the comments too!)

2022-01-04 18:19 UTC, merged